Scopes and validations
gitalek/old-test-guru pull request #6
Opened 2018-11-02 06:42 UTC by gitalek

2018-11-02 14:13 UTC, psylone requested changes

2018-11-02 14:13 UTC, psylone commented on app/models/question.rb
> +  has_many :right_answers, -> { where(correct: true) }, class_name: 'Answer'
Скоуп должен быть в модели Ответа. Ассоциация нужна чтобы выбрать варианты ответов при отображении вопроса во время прохождения теста. Там могут быть как правильные ответы, так и неправильные. Поэтому ассоциация `right_answers` не нужна.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> +    .pluck(:title)
Скоуп должен возвращать объекты класса `ActiveRecord::Relation` чтобы их можно было по цепочке вызывать с другими скоупами, ассоциациями или методами ActiveRecord, поэтому `pluck` необходимо вынести за пределы скоупа.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> +    .pluck(:title)
Сортировку тоже стоит вынести за пределы скоупа.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> -  def self.select_by_category(category)
С учетом комментариев, этот метод нам понадобится.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> +  # end
Закомментированный код необходимо удалить, есть git в случае чего.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> +  scope :hard,   -> { where(level: 3..Float::INFINITY) }
Здесь можно использовать скоуп `by_level`:

```ruby
scope :simple, -> { by_level(0..1) }
```

2018-11-02 14:13 UTC, psylone commented on app/models/answer.rb
> +    limit = question.class::ANSWERS_MAX_LIMIT
`Question::ANSWERS_MAX_LIMIT`.

2018-11-02 14:13 UTC, psylone commented on app/models/answer.rb
> +  validate :validate_answers_limit
Нужно запускать валидацию только при создании ответа, иначе не сможем отредактировать если у вопроса есть 4 ответа.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> +  validate :validate_level_title_uniqueness
Используй стандартную валидацию.

2018-11-02 14:13 UTC, psylone commented on app/models/test.rb
> +  validate :validate_level_title_uniqueness
Также необходимо добавить составной уникальный индекс в базе данных.

2018-11-03 05:16 UTC, gitalek commented on app/models/test.rb
> +  scope :hard,   -> { where(level: 3..Float::INFINITY) }
fixed

2018-11-03 05:16 UTC, gitalek commented on app/models/test.rb
> +  # end
fixed

2018-11-03 05:17 UTC, gitalek commented on app/models/test.rb
> -  def self.select_by_category(category)
ok, использовал этот метод для вывода конечного значения (посредством скоупа by_category)

2018-11-03 05:17 UTC, gitalek commented on app/models/test.rb
> +    .pluck(:title)
fixed

2018-11-03 05:26 UTC, gitalek commented on app/models/answer.rb
> +    limit = question.class::ANSWERS_MAX_LIMIT
Поправил.

Этот способ как-то существенно неправильный или чем-то предпочтительнее второй вариант с обращенимем по имени? Я специально не стал захардкоживать имя класса. Понимаю, что здесь всё повязано конвенциями и просто так имя класса вопроса не поменяется, но тем не менее.

2018-11-03 05:29 UTC, gitalek commented on app/models/answer.rb
> +  validate :validate_answers_limit
fixed

2018-11-03 05:57 UTC, gitalek commented on app/models/test.rb
> +  validate :validate_level_title_uniqueness
fixed

2018-11-03 06:15 UTC, gitalek commented on app/models/question.rb
> +  has_many :right_answers, -> { where(correct: true) }, class_name: 'Answer'
Не понял задачи. Прочитал несколько раз условие и твой комментарий и всё равно не понял, что требуется сделать.

> Ассоциация нужна чтобы выбрать варианты ответов при отображении вопроса во время прохождения теста.

Все варианты ответов (правильные и неправильные) для конкретного вопроса достаются через ассоциацию вопроса `answers`.

> Там могут быть как правильные ответы, так и неправильные. Поэтому ассоциация right_answers не нужна.

В  задании написано: "для выбора правильных ответов". Так как я вижу смысл выбирать правильные ответы не "вообще", а для конкретного вопроса, то добавил ассоциацию (со скоупом), делающую это.

Скоуп в модели Ответа, условно, работает как метод класса. Мне же нужны правильные ответы, привязанные к конкретному вопросу. А их проще всего получить из ассоциации модели вопроса. Или нужно сделать скоуп в модели Ответа, который бы принимал параметром индекс вопроса и возвращал список правильных ответов?

2018-11-03 14:10 UTC, psylone commented on app/models/question.rb
> +  has_many :right_answers, -> { where(correct: true) }, class_name: 'Answer'
Скоупы можно вызывать по цепочке с методами ассоциаций, другими скоупами или методами ActiveRecord:

```ruby
question.answers.correct
```

2018-11-03 14:11 UTC, psylone commented on app/models/answer.rb
> +    limit = question.class::ANSWERS_MAX_LIMIT
Ход мыслей верный, но здесь мудрить не стоит.

2018-11-03 14:12 UTC, psylone approved these changes

2018-11-04 07:05 UTC, gitalek commented on app/models/question.rb
> +  has_many :right_answers, -> { where(correct: true) }, class_name: 'Answer'
Ok, понял, исправил. В моей реализации вызов `question.answers.correct` возвращает тип `ActiveRecord::AssociationRelation`, так как correct это скоуп. Это нормально для текущей задачи или надо допиливать результат до конкретного значения со "стандартным" типом Ruby (например, массив объектов)?

2018-11-04 07:06 UTC, merged

2018-11-04 11:35 UTC, psylone commented on app/models/question.rb
> +  has_many :right_answers, -> { where(correct: true) }, class_name: 'Answer'
Нет, нужен именно релейшен, всё хорошо.